color0 #181c24
color1 #d15c74
color2 #89c983
color3 #e0af68
color4 #7b9ade
color5 #9a84c6
color6 #66c4d8
color7 #989ca7
color8 #434a62
color9 #e76b83
color10 #93cb77
color11 #ff9e64
color12 #7a9ee9
color13 #aa8fde
color14 #a3d8f7
color15 #dbdee6

cursor                #7b9ade
cursor_text_color     #1a1e28
background            #1a1e28
foreground            #dbdee6
selection_foreground  #1a1e28
selection_background  #7b9ade
active_border_color   #7b9ade
inactive_border_color #323847
url_color             #7b9ade

active_tab_foreground   #1a1e28
active_tab_background   #7b9ade
inactive_tab_foreground #989ca7
inactive_tab_background #323847
cursor_trail_color      #989ca7
