
[font]
size = 14

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[window]
opacity = 0.95

[env]
term = "xterm-256color"
# WINIT_X11_SCALE_FACTOR = "1.3"

[general]
# import = ["~/.config/alacritty/rose-pine.toml"]
# import = ["~/.config/alacritty/kanagawa_wave.toml"]
import = ["~/.config/alacritty/tokyonight_night.toml"]

[terminal]

# [terminal.shell]
# program = "tmux"
# args = ["-2", "-u"]
