# import = ["~/.config/alacritty/rose-pine.toml"]
# import = ["~/.config/alacritty/kanagawa_wave.toml"]
import = ["~/.config/alacritty/tokyonight_night.toml"]

[font]
size = 10

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Regular"

[window]
opacity = 0.95

[env]
WINIT_X11_SCALE_FACTOR = "1.3"
term = "xterm-256color"
